"""empty message

Revision ID: 26792a2cfa51
Revises: 2323fe16b89d
Create Date: 2020-03-14 20:01:04.402494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26792a2cfa51'
down_revision = '2323fe16b89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('date_joined', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'date_joined')
    # ### end Alembic commands ###
